language: python

python:
  - "3.6"      
  - "3.7"
  - "3.8"

env:
  - DJANGO_VERSION=2.0.0
  - DJANGO_VERSION=3.0.0

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install coverage
  - pip install pipenv
  - pipenv install --dev

script: 
  - cd src
  - python manage.py migrate
  - python manage.py loaddata settings.json
  - coverage run manage.py test

after_success: coverage report
