version: '3.7'

services:
    web:
        build:
            context: ./app
            dockerfile: Dockerfile.prod
        command: gunicorn new_shows.wsgi:application --bind 0.0.0.0:1337 --preload
        volumes:
            - static_volume:/home/app/web/staticfiles
        expose:
            - 1337
        ports:
            - 1337:1337
        env_file:
            - ./.env.prod
volumes:
    static_volume:
