# Generated by Django 3.0.1 on 2019-12-27 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10)),
                ('timezone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvmaze_id', models.IntegerField()),
                ('network', models.CharField(max_length=30)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newshows.Country')),
            ],
        ),
        migrations.CreateModel(
            name='ShowType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvmaze_id', models.IntegerField()),
                ('url', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('runtime', models.IntegerField()),
                ('premiere', models.DateTimeField()),
                ('tvrage_id', models.CharField(max_length=10)),
                ('thetvdb_id', models.CharField(max_length=10)),
                ('imdb_id', models.CharField(max_length=10)),
                ('genre', models.ManyToManyField(to='newshows.Genre')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newshows.Language')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newshows.Network')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newshows.Status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newshows.ShowType')),
            ],
        ),
    ]
