# Generated by Django 3.0.1 on 2019-12-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'verbose_name_plural': 'Networks'},
        ),
        migrations.AlterModelOptions(
            name='show',
            options={'verbose_name_plural': 'Shows'},
        ),
        migrations.AlterModelOptions(
            name='showtype',
            options={'verbose_name_plural': 'Show Types'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
    ]
