# Generated by Django 3.0.2 on 2020-01-12 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newshows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='newshows.Profile'),
        ),
    ]
