# Generated by Django 3.0.2 on 2020-01-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshows', '0002_setting_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='addmonitored',
            field=models.BooleanField(default=True),
        ),
    ]
