# Generated by Django 3.0.1 on 2019-12-27 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newshows', '0002_auto_20191227_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webchannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvmaze_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Webchannels',
            },
        ),
        migrations.AlterField(
            model_name='show',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newshows.Network'),
        ),
        migrations.AddField(
            model_name='show',
            name='webchannel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newshows.Webchannel'),
        ),
    ]
