# Generated by Django 3.0.1 on 2019-12-27 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newshows', '0003_auto_20191227_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newshows.Country'),
        ),
        migrations.AlterField(
            model_name='webchannel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newshows.Country'),
        ),
    ]
