# Generated by Django 3.0.4 on 2020-03-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshows', '0004_auto_20200112_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='SONARR_APIKEY',
            field=models.CharField(blank=True, max_length=30, verbose_name='Sonarr API-Key'),
        ),
        migrations.AddField(
            model_name='setting',
            name='SONARR_OK',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='setting',
            name='SONARR_ROOTFOLDER',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Sonarr Rootfolder'),
        ),
        migrations.AddField(
            model_name='setting',
            name='SONARR_URL',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Sonarr URL'),
        ),
    ]
