# Generated by Django 3.0.1 on 2019-12-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshows', '0004_auto_20191227_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='page',
        ),
        migrations.AddField(
            model_name='settings',
            name='setting',
            field=models.CharField(default='page', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='value',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
