# Generated by Django 3.0.4 on 2020-03-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshows', '0005_auto_20200313_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='SONARR_APIKEY',
            field=models.CharField(blank=True, max_length=40, verbose_name='Sonarr API-Key'),
        ),
    ]
