# Generated by Django 3.0.1 on 2019-12-27 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newshows', '0005_auto_20191227_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='network',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='newshows.Network'),
        ),
        migrations.AlterField(
            model_name='show',
            name='webchannel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='newshows.Webchannel'),
        ),
    ]
