# Generated by Django 3.0.1 on 2019-12-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshows', '0006_auto_20191227_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='imdb_id',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='runtime',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='thetvdb_id',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='tvrage_id',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
