# Generated by Django 3.0.1 on 2019-12-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshows', '0007_auto_20191227_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='premiere',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
