# Generated by Django 3.0.4 on 2020-03-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshows', '0008_auto_20200320_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='page',
            field=models.IntegerField(default=0),
        ),
    ]
