# Generated by Django 3.0.1 on 2019-12-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshows', '0008_auto_20191227_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='runtime',
            field=models.IntegerField(default=0),
        ),
    ]
