# Generated by Django 3.0.1 on 2019-12-28 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newshows', '0009_auto_20191227_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='language',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='newshows.Language'),
        ),
        migrations.AlterField(
            model_name='showtype',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
