# Generated by Django 3.0.4 on 2020-03-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshows', '0009_auto_20200320_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='FIRSTRUN',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
