# Generated by Django 3.0.7 on 2020-06-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshows', '0009_auto_20200320_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='imdb_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='thetvdb_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='tvrage_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
