# Generated by Django 3.0.4 on 2020-03-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshows', '0010_setting_firstrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('pic', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('author', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.AlterField(
            model_name='show',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
