# Generated by Django 3.0.7 on 2020-06-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshows', '0010_auto_20200617_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='network',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='show',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Show'),
        ),
        migrations.AlterField(
            model_name='webchannel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
