# Generated by Django 3.0.1 on 2019-12-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshows', '0011_auto_20191229_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='ignored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='show',
            name='insonarr',
            field=models.BooleanField(default=False),
        ),
    ]
