# Generated by Django 3.0.4 on 2020-03-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshows', '0011_auto_20200328_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='score2',
            field=models.IntegerField(default=0),
        ),
    ]
