# Generated by Django 3.0.1 on 2020-01-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshows', '0012_auto_20191229_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='ignored',
            field=models.BooleanField(default=False, verbose_name='I'),
        ),
        migrations.AlterField(
            model_name='show',
            name='insonarr',
            field=models.BooleanField(default=False, verbose_name='S'),
        ),
        migrations.AlterField(
            model_name='show',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Show'),
        ),
        migrations.AlterField(
            model_name='show',
            name='premiere',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='premiered'),
        ),
    ]
