# Generated by Django 3.0.1 on 2020-01-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshows', '0013_auto_20200102_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='value',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
