# Generated by Django 3.0.1 on 2020-01-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshows', '0014_auto_20200102_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='setting',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
