# Generated by Django 3.0.1 on 2020-01-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshows', '0016_auto_20200106_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(blank=True, default=None, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
