# Generated by Django 3.0.1 on 2020-01-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshows', '0017_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
