# Generated by Django 3.0.2 on 2020-01-08 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newshows', '0019_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='sonarr_ok',
            field=models.BooleanField(default=False, verbose_name='Settings for Sonarr ok'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='sonarr_apikey',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Sonarr API Key'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='sonarr_autoadd',
            field=models.BooleanField(default=False, verbose_name='Auto add shows to Sonarr'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='sonarr_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newshows.Profile', verbose_name='Sonarr Profile ID'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='sonarr_url',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Sonarr URL'),
        ),
    ]
