# Generated by Django 3.0.4 on 2020-03-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshows', '0006_auto_20200314_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='last_tvmaze_full_update',
            field=models.DateField(default='1970-01-01'),
        ),
    ]
