version: '3'

services:
  redis:
    image: redis
    networks:
      - redis-net
    ports:
      - "6379:6379"
  web:
    env_file:
      - .env
    networks:
      - redis-net 
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis

networks:
  redis-net:
