# pull official base image
FROM python:3.8.0-alpine

# set work directory
WORKDIR /p4s

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt /p4s/requirements.txt
RUN pip install -r requirements.txt

COPY . /p4s/entrypoint.sh

ENTRYPOINT ["/usr/src/app/entrypoint.dev.sh"]
